name: Deploy Azure Functions (Python 3.11)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_426CF3E234DE4CDBADBDCA8821D835ED }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2FBA0C6C69594296872EAA4DF1CA2890 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E98FEEF24184F78BA5FBFE03B50A563 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: func-profiles-bigdata
          package: .     # raíz del repo (host.json, function_app.py, requirements.txt)
